version: '3.8'

services:
  web:
    build: ./Api
    volumes:
      - ./Api:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT_ID=${AZURE_OPENAI_DEPLOYMENT_ID}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
    depends_on:
      - db
    networks:
      - app-network 
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    networks:
      - app-network # Connect to the network to be used by other containers (ej: the web server)
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks: # All the networks that connects our containers
  app-network:
    driver: bridge

volumes:
  postgres_data:
