# Usa una imagen base oficial de Python
FROM python:3.11.1-slim

# Actualiza pip
RUN pip install --upgrade pip

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY packages.py .
RUN python packages.py

# Copia el resto del código fuente en el contenedor
COPY . .

# Define el comando por defecto para ejecutar la aplicación
CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]

